### ISSUE TITLE
Typos in the code

### ISSUE THREAD

**Issue by atkinsroy** [HewlettPackard/HPEDSCC-PowerShell-Toolkit#2]
Hi Chris,

This is a good start. There are a few typo's in the code - for example "clear-varibable" in Controller.ps1. There are some non-English words appearing in the help files.  There are some references to Alletra9K when you mean Alletra5/6K. A suggestion - edit the code in VS Code with the PowerShell module installed. It'll will detect errors for you. As an added bonus, it will realign your code in accordance with best practice!

I'd be happy to contribute to this project to add functionality to the module, but you don't appear to be merging in pull requests. Let me know.

**Comment by chris-lionetti** [comment]
I really appreciate pointing these mistakes out to me. Yes I also use (and love) VS-Code, and use heavily the autocorrect features, but I am the only author of this toolkit, there is no team behind this, and its quite a task to write 6400 bug free lines. I am trying though. If you open more bugs like this to either the code or the documentation, I will endeavor to fix them quickly. I still can't believe I used clear-Varibable...That is just...funny.

**Comment by chris-lionetti** [comment]
I have just uploaded the fix for these :)
